---

- name: "{{ ovpn_data_conf }} directory create"
  ansible.builtin.file:
    path: "{{ ovpn_data_conf }}"
    state: directory
    mode: '0755'
  become: true

- name: copy ovpn_env.sh
  template:
    src: "ovpn_env.sh.j2"
    dest: "{{ ovpn_data_conf }}/ovpn_env.sh"
    mode: 0755
  become: true

- name: copy openvpn.conf
  template:
    src: "openvpn.conf.j2"
    dest: "{{ ovpn_data_conf }}/openvpn.conf"
    mode: 0755
  become: true
  notify: 
    - restart

- name: pki exist?
  stat:
    path: "{{ ovpn_data_pki }}"
  register: result
  
- name: copy init-pki script
  template:
    src: "init-pki.exp.j2"
    dest: "/home/{{ ansible_user }}/init-pki.exp"
    mode: 0700
  environment: "{{ ovpn_env }}"
  when: not result.stat.exists

- name: init-pki
  shell: "/home/{{ ansible_user }}/init-pki.exp"
  args:
    executable: /bin/bash
  notify: 
    - restart
  environment: "{{ ovpn_env }}"
  become: true
  when: not result.stat.exists

- name: copy build-client script
  template:
    src: "build-client.exp.j2"
    dest: "/home/{{ ansible_user }}/build-client.exp"
    mode: 0700

- name: copy revoke-client script 
  template:
    src: "revoke-client.exp.j2"
    dest: "/home/{{ ansible_user }}/revoke-client.exp"
    mode: 0700
  
- name: "{{ ovpn_data_accs }} directory create"
  ansible.builtin.file:
    path: "{{ ovpn_data_accs }}"
    state: directory
    mode: '0700'
  become: true

