---

- name: common
  include_tasks: common.yml  

- name: install
  include_tasks: install.yml

- name: config push
  include_tasks: config-push.yml
  
- name: config
  include_tasks: config.yml
    
- name: config pull
  include_tasks: config-pull.yml

- name: ensure ovpn started 
  ansible.builtin.service:
    name: ovpn
    state: started
    enabled: true
  ignore_errors: true
  become: true

  
