---

- include_tasks: common.yml  
- include_tasks: install.yml
- include_tasks: config.yml
    
- name: ovpn started 
  ansible.builtin.service:
    name: ovpn
    state: started
    enabled: true
  ignore_errors: true
  become: true
