---

- include_tasks: common.yml  

- include_tasks: install.yml

- include_tasks: config-push.yml
  when: ovpn_config_push
  
- include_tasks: config.yml
    
- include_tasks: config-pull.yml
  when: not ovpn_config_push

- name: ovpn started 
  ansible.builtin.service:
    name: ovpn
    state: started
    enabled: true
  ignore_errors: true
  become: true

  
