---

- name: client request for {{ client_name }} exist?
  stat:
    path: "{{ ovpn_data_config }}/pki/reqs/{{ client_name }}.req"
  become: true
  register: result

- name: revoke & delete acc 
  when: result.stat.exists
  block:
    - name: revoke client - {{ client_name }}
      shell: "/home/{{ ansible_user }}/revoke-client.exp {{ client_name }}"
      args:
        executable: /bin/bash

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: "{{ ovpn_data_accs }}/{{ client_name }}.ovpn"
        state: absent
  notify:
    - restart
